/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementBar: typeof import('./../components/AnnouncementBar.vue')['default']
    EditStepsDialog: typeof import('./../components/EditStepsDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExecutionProgressPanel: typeof import('./../components/ExecutionProgressPanel.vue')['default']
    FeedbackDialog: typeof import('./../components/FeedbackDialog.vue')['default']
    LogListPanel: typeof import('./../components/LogListPanel.vue')['default']
    MonitorDialog: typeof import('./../components/MonitorDialog.vue')['default']
    MonitorDiffView: typeof import('./../components/MonitorDiffView.vue')['default']
    MonitorPanel: typeof import('./../components/MonitorPanel.vue')['default']
    PageSkeleton: typeof import('./../components/PageSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunScriptDialog: typeof import('./../components/RunScriptDialog.vue')['default']
    SaveScriptDialog: typeof import('./../components/SaveScriptDialog.vue')['default']
    ScriptCard: typeof import('./../components/ScriptCard.vue')['default']
    ScriptDataDialog: typeof import('./../components/ScriptDataDialog.vue')['default']
    SettingsPanel: typeof import('./../components/SettingsPanel.vue')['default']
    StepListEditor: typeof import('./../components/StepListEditor.vue')['default']
    UpdateNotifier: typeof import('./../components/UpdateNotifier.vue')['default']
    VersionInfo: typeof import('./../components/VersionInfo.vue')['default']
  }
}
